version: "3"

tasks:
  build:
    cmds:
      - go build -o bin/yom cmd/main.go

  run:
    cmds:
      - task build && ./bin/yom {{ .CLI_ARGS }}

  dev:
    cmds:
      - task build && ./bin/yom ~/dev/go/yom/ressources/grocery-list-05.02.25.txt
